version: 2

jobs:
  build-image:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build controller image
          command: make controller
          no_output_timeout: 20m

  push-image:
    machine:
      docker_layer_caching: true
    environment:
      GORDO_PROD_MODE: true
    steps:
      - checkout
      - run:
          name: Push Image
          command: |
            echo $(docker images)
            make push-prod-controller

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-image:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              only: master
            tags:
              only: /.*/
