jobs:

  build-controller-image:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build controller image
          command: make gordo-controller

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-controller-image
